/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.PiHerosGames.Telas;

import controller.ControllerProdutos;
import java.util.ArrayList;
import model.ModelProdutos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eders
 */
public class TelaConsultaProdutos extends javax.swing.JFrame {
    ModelProdutos modelProdutos = new ModelProdutos();
    ArrayList<ModelProdutos> listaProdutos = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();

    /**
     * Creates new form TelaConsultaProdutos
     */
   

    public TelaConsultaProdutos() {
        initComponents();
        garregarProdutos();
        habilitarDesabilitarCampos(false);
    }

    //Preenche a tabela de produtos
    private void garregarProdutos() {
        listaProdutos = controllerProdutos.getListaProdutosController();
        DefaultTableModel modelo = (DefaultTableModel) tbl_dadosProd.getModel();
        modelo.setNumRows(0);
        // Inserção de produtos na tabela
        int cont = listaProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
               listaProdutos.get(i).getIdtb_vendas(),
               listaProdutos.get(i).getNome_produto(),
               listaProdutos.get(i).getMarca_produto(),
               listaProdutos.get(i).getPreco_produtos(),
               listaProdutos.get(i).getCaracteristica_produtos(),
               listaProdutos.get(i).getEstoque_produtos()
            });
        }
    }
    private void habilitarDesabilitarCampos(boolean condicao){
        txt_nomeProd.setEnabled(condicao);
        txt_MarcaProd.setEnabled(condicao);
        txt_precoProd.setEnabled(condicao);
        txt_caractProd.setEnabled(condicao);
        txt_estoqueProd.setEnabled(condicao);
    }
    
    public void getValuesModelProduto(ModelProdutos pModelProdutos) {
        this.txt_idProd.setText(Integer.toString(pModelProdutos.getIdtb_vendas()));
        this.txt_nomeProd.setText(pModelProdutos.getNome_produto());
        this.txt_MarcaProd.setText(pModelProdutos.getMarca_produto());
        this.txt_precoProd.setText(Double.toString(pModelProdutos.getPreco_produtos()));
        this.txt_caractProd.setText(pModelProdutos.getCaracteristica_produtos());
        this.txt_estoqueProd.setText( Integer.toString(pModelProdutos.getEstoque_produtos()));
    }
    
    public void LimparPainel() {
        txt_idProd.setText(null);
        txt_nomeProd.setText(null);
        txt_MarcaProd.setText(null);
        txt_precoProd.setText(null);
        txt_estoqueProd.setText(null);
        txt_caractProd.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_nomeProd = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_idProd = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_dadosProd = new javax.swing.JTable();
        btn_cancelar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_MarcaProd = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_precoProd = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_caractProd = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_estoqueProd = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        btn_editar1 = new javax.swing.JButton();
        btn_Atualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txt_nomeProd);

        jLabel2.setText("Nome:");

        txt_idProd.setEditable(false);
        txt_idProd.setEnabled(false);
        jScrollPane2.setViewportView(txt_idProd);

        jLabel3.setText("Código :");

        tbl_dadosProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Marca", "Preco", "Caracteristica", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbl_dadosProd);

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/PiHerosGames/Icones/block.png"))); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/PiHerosGames/Icones/Close.png"))); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/PiHerosGames/Icones/Editar.png"))); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/PiHerosGames/Icones/sair.png"))); // NOI18N
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txt_MarcaProd);

        jLabel4.setText("Marca :");

        jScrollPane4.setViewportView(txt_precoProd);

        jLabel5.setText("Característica :");

        jScrollPane5.setViewportView(txt_caractProd);

        jLabel6.setText("Preço :");

        jScrollPane6.setViewportView(txt_estoqueProd);

        jLabel7.setText("Estoque :");

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/PiHerosGames/Icones/folder-plus.png"))); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/PiHerosGames/Icones/Add.png"))); // NOI18N
        btn_editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar1ActionPerformed(evt);
            }
        });

        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.setEnabled(false);
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Atualizar)
                                .addGap(102, 102, 102)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_sair)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar)
                .addGap(27, 27, 27)
                .addComponent(btn_excluir)
                .addGap(28, 28, 28)
                .addComponent(btn_editar)
                .addGap(30, 30, 30)
                .addComponent(btn_editar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salvar)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Atualizar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_cancelar)
                            .addComponent(btn_sair)
                            .addComponent(btn_excluir)
                            .addComponent(btn_editar)))
                    .addComponent(btn_salvar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_editar1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
       PaginaInicial inicio = new PaginaInicial();
       inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        LimparPainel();
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        
        modelProdutos.setNome_produto(this.txt_nomeProd.getText());
        modelProdutos.setMarca_produto(this.txt_MarcaProd.getText());
        modelProdutos.setPreco_produtos(Double.parseDouble(this.txt_precoProd.getText()));
        modelProdutos.setCaracteristica_produtos(this.txt_caractProd.getText());
        modelProdutos.setEstoque_produtos(Integer.parseInt(this.txt_estoqueProd.getText()));
        if(controllerProdutos.salvarProdutosController(modelProdutos) > 0){
            JOptionPane.showMessageDialog(null, "Produto Cadastrado com sucesso!");
            LimparPainel();
            this.garregarProdutos();
            this.habilitarDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar !");
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tbl_dadosProd.getSelectedRow();
        int pIdtb_vendas = (int) tbl_dadosProd.getValueAt(linha, 0);
        int deletar = JOptionPane.showConfirmDialog(null, " Tem certeza que deseja excluir o produto ?", "Atenção", JOptionPane.YES_NO_OPTION);
        
        
        if(deletar == JOptionPane.YES_OPTION){
            if(controllerProdutos.excluirProdutosController(pIdtb_vendas)){
                JOptionPane.showMessageDialog(null, "Produto Deletado com sucesso!");
                LimparPainel();
                this.garregarProdutos();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao Deletar !");
            }
            
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar1ActionPerformed
        habilitarDesabilitarCampos(true);
    }//GEN-LAST:event_btn_editar1ActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        this.habilitarDesabilitarCampos(true);
        int linhaSelect = tbl_dadosProd.getSelectedRow();
        int codigoProdSelect = (int) tbl_dadosProd.getValueAt(linhaSelect, 0);
        btn_Atualizar.setEnabled(true);
        try {
            modelProdutos = controllerProdutos.getProdutosController(codigoProdSelect);
            getValuesModelProduto(modelProdutos);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        int editar = JOptionPane.showConfirmDialog(null, " Tem certeza que deseja Editar o produto ?", "Atenção", JOptionPane.YES_NO_OPTION);
        modelProdutos.setIdtb_vendas(Integer.parseInt(this.txt_idProd.getText()));
        modelProdutos.setNome_produto(this.txt_nomeProd.getText());
        modelProdutos.setMarca_produto(this.txt_MarcaProd.getText());
        modelProdutos.setPreco_produtos(Double.parseDouble(this.txt_precoProd.getText()));
        modelProdutos.setCaracteristica_produtos(this.txt_caractProd.getText());
        modelProdutos.setEstoque_produtos(Integer.parseInt(this.txt_estoqueProd.getText()));
         if(editar == JOptionPane.YES_OPTION){
            if(controllerProdutos.atualizarProdutosController(modelProdutos)){
                JOptionPane.showMessageDialog(null, "Produto Atualizado com sucesso!");
                LimparPainel();
                this.habilitarDesabilitarCampos(false);
                this.garregarProdutos();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao Atualizar !");
            }
        }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_editar1;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tbl_dadosProd;
    private javax.swing.JTextPane txt_MarcaProd;
    private javax.swing.JTextPane txt_caractProd;
    private javax.swing.JTextPane txt_estoqueProd;
    private javax.swing.JTextPane txt_idProd;
    private javax.swing.JTextPane txt_nomeProd;
    private javax.swing.JTextPane txt_precoProd;
    // End of variables declaration//GEN-END:variables
}
